apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: 'C:\Users\zarcr\Documents\test2\init.sql'
